name: myenv
channels:
  - defaults
dependencies:
  - python=3.8  # Projenizin Python sürümüne göre değiştirin
  - numpy  # Eğer numpy kullanıyorsanız
  - pandas  # Eğer pandas kullanıyorsanız
  - scikit-learn  # Eğer scikit-learn kullanıyorsanız
  - pytest  # Eğer testler için pytest kullanıyorsanız
  - pip:
    - flask  # Eğer Flask kullanıyorsanız
    - requests  # Eğer requests kullanıyorsanız
