name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: 107694014550368741689


    - name: Build and push Docker image
      run: |
        # Docker imajını build etme ve push etme komutları

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-gke-cluster --zone europe-west3 --project 107694014550368741689


    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
